# Generated by Django 3.2.9 on 2021-11-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'symbol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BarDataWeekly',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_weekly',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='BarDataMonthly',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_monthly',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='BarDataDaily',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_daily',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='BarData5Min',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_5min',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='BarData30Min',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_30min',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='BarData1Min',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_1min',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='BarData1H',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_1h',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='BarData15Min',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('dividend_amount', models.FloatField(blank=True, null=True)),
                ('split_coeff', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.symbol')),
            ],
            options={
                'db_table': 'bar_data_15min',
                'managed': True,
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
    ]
