"""added equities, daily_price, weekly_price, and monthly_price tables

Revision ID: 58506a9f220c
Revises: 
Create Date: 2021-11-16 11:08:06.391209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58506a9f220c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_data_daily',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    op.create_table('bar_data_monthly',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    op.create_table('bar_data_weekly',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    op.create_table('symbols',
    sa.Column('symbol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbols')
    op.drop_table('bar_data_weekly')
    op.drop_table('bar_data_monthly')
    op.drop_table('bar_data_daily')
    # ### end Alembic commands ###
