"""empty message

Revision ID: 5df8c36f63cf
Revises: fb72bd5a5a2d
Create Date: 2021-11-15 19:25:56.474413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df8c36f63cf'
down_revision = 'fb72bd5a5a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_data_daily',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('equity_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'equity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bar_data_daily')
    # ### end Alembic commands ###
