"""refactored price tables with BarData mixin

Revision ID: 85aa4468e8a4
Revises: f928a49ef7ce
Create Date: 2021-11-19 01:27:21.388429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85aa4468e8a4'
down_revision = 'f928a49ef7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bar_data_15min', 'symbol', ['symbol_id'], ['symbol_id'])
    op.add_column('bar_data_1h', sa.Column('split_coeff', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bar_data_1h', 'symbol', ['symbol_id'], ['symbol_id'])
    op.add_column('bar_data_1min', sa.Column('split_coeff', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bar_data_1min', 'symbol', ['symbol_id'], ['symbol_id'])
    op.add_column('bar_data_30min', sa.Column('split_coeff', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bar_data_30min', 'symbol', ['symbol_id'], ['symbol_id'])
    op.add_column('bar_data_5min', sa.Column('split_coeff', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bar_data_5min', 'symbol', ['symbol_id'], ['symbol_id'])
    op.create_foreign_key(None, 'bar_data_daily', 'symbol', ['symbol_id'], ['symbol_id'])
    op.add_column('bar_data_monthly', sa.Column('split_coeff', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bar_data_monthly', 'symbol', ['symbol_id'], ['symbol_id'])
    op.add_column('bar_data_weekly', sa.Column('split_coeff', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bar_data_weekly', 'symbol', ['symbol_id'], ['symbol_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bar_data_weekly', type_='foreignkey')
    op.drop_column('bar_data_weekly', 'split_coeff')
    op.drop_constraint(None, 'bar_data_monthly', type_='foreignkey')
    op.drop_column('bar_data_monthly', 'split_coeff')
    op.drop_constraint(None, 'bar_data_daily', type_='foreignkey')
    op.drop_constraint(None, 'bar_data_5min', type_='foreignkey')
    op.drop_column('bar_data_5min', 'split_coeff')
    op.drop_constraint(None, 'bar_data_30min', type_='foreignkey')
    op.drop_column('bar_data_30min', 'split_coeff')
    op.drop_constraint(None, 'bar_data_1min', type_='foreignkey')
    op.drop_column('bar_data_1min', 'split_coeff')
    op.drop_constraint(None, 'bar_data_1h', type_='foreignkey')
    op.drop_column('bar_data_1h', 'split_coeff')
    op.drop_constraint(None, 'bar_data_15min', type_='foreignkey')
    # ### end Alembic commands ###
