"""renamed symbols > symbol

Revision ID: 9939b253c5d7
Revises: f928a49ef7ce
Create Date: 2021-11-19 10:12:21.611691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9939b253c5d7'
down_revision = 'f928a49ef7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('symbol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('asset_type', sa.String(length=30), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol_id', name=op.f('pk_symbol'))
    )
    op.drop_table('symbols')
    with op.batch_alter_table('bar_data_15min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_coeff', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_15min_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('bar_data_1h', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_coeff', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_1h_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('bar_data_1min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_coeff', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_1min_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('bar_data_30min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_coeff', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_30min_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('bar_data_5min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_coeff', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_5min_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('bar_data_daily', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_daily_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('bar_data_monthly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_coeff', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_monthly_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('bar_data_weekly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_coeff', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bar_data_weekly_symbol_id_symbol'), 'symbol', ['symbol_id'], ['symbol_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_data_weekly', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_weekly_symbol_id_symbol'), type_='foreignkey')
        batch_op.drop_column('split_coeff')

    with op.batch_alter_table('bar_data_monthly', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_monthly_symbol_id_symbol'), type_='foreignkey')
        batch_op.drop_column('split_coeff')

    with op.batch_alter_table('bar_data_daily', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_daily_symbol_id_symbol'), type_='foreignkey')

    with op.batch_alter_table('bar_data_5min', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_5min_symbol_id_symbol'), type_='foreignkey')
        batch_op.drop_column('split_coeff')

    with op.batch_alter_table('bar_data_30min', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_30min_symbol_id_symbol'), type_='foreignkey')
        batch_op.drop_column('split_coeff')

    with op.batch_alter_table('bar_data_1min', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_1min_symbol_id_symbol'), type_='foreignkey')
        batch_op.drop_column('split_coeff')

    with op.batch_alter_table('bar_data_1h', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_1h_symbol_id_symbol'), type_='foreignkey')
        batch_op.drop_column('split_coeff')

    with op.batch_alter_table('bar_data_15min', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bar_data_15min_symbol_id_symbol'), type_='foreignkey')
        batch_op.drop_column('split_coeff')

    op.create_table('symbols',
    sa.Column('symbol_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('sector', sa.VARCHAR(), nullable=True),
    sa.Column('asset_type', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('last_updated_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('symbol_id', name='pk_symbols')
    )
    op.drop_table('symbol')
    # ### end Alembic commands ###
