"""added intraday tables

Revision ID: 9b7c36041aed
Revises: 58506a9f220c
Create Date: 2021-11-16 12:01:54.952776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7c36041aed'
down_revision = '58506a9f220c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_data_15min',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    op.create_table('bar_data_1h',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    op.create_table('bar_data_1min',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    op.create_table('bar_data_30min',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    op.create_table('bar_data_5min',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adj_close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bar_data_5min')
    op.drop_table('bar_data_30min')
    op.drop_table('bar_data_1min')
    op.drop_table('bar_data_1h')
    op.drop_table('bar_data_15min')
    # ### end Alembic commands ###
