"""added default datetimes to BarData

Revision ID: e89cb4663420
Revises: 9939b253c5d7
Create Date: 2021-11-19 10:20:55.942720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89cb4663420'
down_revision = '9939b253c5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_data_15min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bar_data_1h', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bar_data_1min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bar_data_30min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bar_data_5min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bar_data_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bar_data_monthly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bar_data_weekly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_data_weekly', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('bar_data_monthly', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('bar_data_daily', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('bar_data_5min', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('bar_data_30min', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('bar_data_1min', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('bar_data_1h', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('bar_data_15min', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
