"""added split coefficient col

Revision ID: f928a49ef7ce
Revises: 9b7c36041aed
Create Date: 2021-11-17 11:07:21.540541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f928a49ef7ce'
down_revision = '9b7c36041aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bar_data_daily', sa.Column('split_coeff', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bar_data_daily', 'split_coeff')
    # ### end Alembic commands ###
