"""empty message

Revision ID: fb72bd5a5a2d
Revises: 
Create Date: 2021-11-15 15:16:49.411061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb72bd5a5a2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equities',
    sa.Column('equity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('equity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equities')
    # ### end Alembic commands ###
