# Generated by Django 3.2.9 on 2021-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'symbol',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Symbols',
        ),
        migrations.AlterModelOptions(
            name='alembicversion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardata15min',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardata1h',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardata1min',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardata30min',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardata5min',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardatadaily',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardatamonthly',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bardataweekly',
            options={'managed': True},
        ),
    ]
